#!/bin/bash
yum update -y
yum install -y httpd
echo "<html><h1>Hello from EC2 Auto Scale</h1></html>" > /var/www/html/index.html
systemctl start httpd
systemctl enable httpd

=========================

Download the RPM file
sudo wget https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm 
sudo dnf install mysql80-community-release-el9-1.noarch.rpm -y
sudo rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2023
sudo dnf install mysql-community-client -y

If you need server:
sudo dnf install mysql-community-server -y

sudo systemctl start mysql
sudo systemctl enable mysql

sudo mysql -u root

sudo grep 'temporary password' /var/log/mysqld.log


 =========================

mysql -h database-1-instance-1.c3yagkmgm8ha.us-east-1.rds.amazonaws.com -P 3306 -u admin -p 
